apiVersion: issuer.digicert.com/v1alpha1
kind: DigiCertClusterIssuer
metadata:
  name: digicertclusterissuer-sample
spec:
  url: http://ambassador-dcone.dcone/certificate-authority
  authSecretName: digicert-issuer-credentials
  authMode: apiKey
  issuerID: "DDCA90D5FF6BF9889773C9F4CF08C270"
  accountID: "447295bc-8a7a-41ec-9111-4f0c6f0ce4fc"
  templateID: "0196198F96545084143B237D9E39FC90"
  # caBundleSecretName: digicert-ca-bundle               # optional
