apiVersion: issuer.digicert.com/v1alpha1
kind: DigiCertIssuer
metadata:
  name: digicertissuer-sample
  namespace: default
spec:
  url: https://certificate-authority.cert-manager.svc.cluster.local
  authSecretName: digicert-issuer-credentials
  authMode: standalone
  issuerID: "00000000-0000-0000-0000-000000000000"
  # templateID: "00000000-0000-0000-0000-000000000000"  # optional
  # caBundleSecretName: digicert-ca-bundle               # optional
