apiVersion: issuer.digicert.com/v1alpha1
kind: DigiCertClusterIssuer
metadata:
  name: digicertclusterissuer-sample
spec:
  url: http://ambassador-dcone.dcone/certificate-authority
  authSecretName: digicert-issuer-credentials
  authMode: apiKey
  issuerID: "00000000000000000000000000000000"
  accountID: "000000000000000000000000000000000000"
  templateID: "00000000000000000000000000000000"
  # caBundleSecretName: digicert-ca-bundle               # optional
