apiVersion: issuer.issuer.digicert.com/v1alpha1
kind: DigiCertClusterIssuer
metadata:
  labels:
    app.kubernetes.io/name: digicert-issuer
    app.kubernetes.io/managed-by: kustomize
  name: digicertclusterissuer-sample
spec:
  # TODO(user): Add fields here
